/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as authEmailVerifyIndexRouteImport } from './routes/(auth)/email-verify/index'
import { Route as authEmailResendIndexRouteImport } from './routes/(auth)/email-resend/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/(auth)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/(auth)/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/(auth)/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const authEmailVerifyIndexRoute = authEmailVerifyIndexRouteImport.update({
  id: '/(auth)/email-verify/',
  path: '/email-verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const authEmailResendIndexRoute = authEmailResendIndexRouteImport.update({
  id: '/(auth)/email-resend/',
  path: '/email-resend/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/email-resend': typeof authEmailResendIndexRoute
  '/email-verify': typeof authEmailVerifyIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/email-resend': typeof authEmailResendIndexRoute
  '/email-verify': typeof authEmailVerifyIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(auth)/email-resend/': typeof authEmailResendIndexRoute
  '/(auth)/email-verify/': typeof authEmailVerifyIndexRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/email-resend'
    | '/email-verify'
    | '/forgot-password'
    | '/signin'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/email-resend'
    | '/email-verify'
    | '/forgot-password'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/(auth)/email-resend/'
    | '/(auth)/email-verify/'
    | '/(auth)/forgot-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  authEmailResendIndexRoute: typeof authEmailResendIndexRoute
  authEmailVerifyIndexRoute: typeof authEmailVerifyIndexRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/email-verify/': {
      id: '/(auth)/email-verify/'
      path: '/email-verify'
      fullPath: '/email-verify'
      preLoaderRoute: typeof authEmailVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/email-resend/': {
      id: '/(auth)/email-resend/'
      path: '/email-resend'
      fullPath: '/email-resend'
      preLoaderRoute: typeof authEmailResendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  authEmailResendIndexRoute: authEmailResendIndexRoute,
  authEmailVerifyIndexRoute: authEmailVerifyIndexRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
