/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRoutesRouteRouteImport } from './routes/_protectedRoutes/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRoutesDashboardRouteRouteImport } from './routes/_protectedRoutes/dashboard/route'
import { Route as ProtectedRoutesDashboardIndexRouteImport } from './routes/_protectedRoutes/dashboard/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authResetPasswordIndexRouteImport } from './routes/(auth)/reset-password/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as authEmailVerifyIndexRouteImport } from './routes/(auth)/email-verify/index'
import { Route as authEmailResendIndexRouteImport } from './routes/(auth)/email-resend/index'
import { Route as ProtectedRoutesDashboardSessionsIndexRouteImport } from './routes/_protectedRoutes/dashboard/sessions/index'

const ProtectedRoutesRouteRoute = ProtectedRoutesRouteRouteImport.update({
  id: '/_protectedRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoutesDashboardRouteRoute =
  ProtectedRoutesDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedRoutesRouteRoute,
  } as any)
const ProtectedRoutesDashboardIndexRoute =
  ProtectedRoutesDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedRoutesDashboardRouteRoute,
  } as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => authRouteRoute,
} as any)
const authEmailVerifyIndexRoute = authEmailVerifyIndexRouteImport.update({
  id: '/email-verify/',
  path: '/email-verify/',
  getParentRoute: () => authRouteRoute,
} as any)
const authEmailResendIndexRoute = authEmailResendIndexRouteImport.update({
  id: '/email-resend/',
  path: '/email-resend/',
  getParentRoute: () => authRouteRoute,
} as any)
const ProtectedRoutesDashboardSessionsIndexRoute =
  ProtectedRoutesDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => ProtectedRoutesDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/dashboard': typeof ProtectedRoutesDashboardRouteRouteWithChildren
  '/email-resend': typeof authEmailResendIndexRoute
  '/email-verify': typeof authEmailVerifyIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/dashboard/': typeof ProtectedRoutesDashboardIndexRoute
  '/dashboard/sessions': typeof ProtectedRoutesDashboardSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/email-resend': typeof authEmailResendIndexRoute
  '/email-verify': typeof authEmailVerifyIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/dashboard': typeof ProtectedRoutesDashboardIndexRoute
  '/dashboard/sessions': typeof ProtectedRoutesDashboardSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_protectedRoutes': typeof ProtectedRoutesRouteRouteWithChildren
  '/_protectedRoutes/dashboard': typeof ProtectedRoutesDashboardRouteRouteWithChildren
  '/(auth)/email-resend/': typeof authEmailResendIndexRoute
  '/(auth)/email-verify/': typeof authEmailVerifyIndexRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/_protectedRoutes/dashboard/': typeof ProtectedRoutesDashboardIndexRoute
  '/_protectedRoutes/dashboard/sessions/': typeof ProtectedRoutesDashboardSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/email-resend'
    | '/email-verify'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-resend'
    | '/email-verify'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/dashboard/sessions'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_protectedRoutes'
    | '/_protectedRoutes/dashboard'
    | '/(auth)/email-resend/'
    | '/(auth)/email-verify/'
    | '/(auth)/forgot-password/'
    | '/(auth)/reset-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
    | '/_protectedRoutes/dashboard/'
    | '/_protectedRoutes/dashboard/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ProtectedRoutesRouteRoute: typeof ProtectedRoutesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protectedRoutes': {
      id: '/_protectedRoutes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedRoutes/dashboard': {
      id: '/_protectedRoutes/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedRoutesDashboardRouteRouteImport
      parentRoute: typeof ProtectedRoutesRouteRoute
    }
    '/_protectedRoutes/dashboard/': {
      id: '/_protectedRoutes/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedRoutesDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoutesDashboardRouteRoute
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/email-verify/': {
      id: '/(auth)/email-verify/'
      path: '/email-verify'
      fullPath: '/email-verify'
      preLoaderRoute: typeof authEmailVerifyIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/email-resend/': {
      id: '/(auth)/email-resend/'
      path: '/email-resend'
      fullPath: '/email-resend'
      preLoaderRoute: typeof authEmailResendIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_protectedRoutes/dashboard/sessions/': {
      id: '/_protectedRoutes/dashboard/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof ProtectedRoutesDashboardSessionsIndexRouteImport
      parentRoute: typeof ProtectedRoutesDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authEmailResendIndexRoute: typeof authEmailResendIndexRoute
  authEmailVerifyIndexRoute: typeof authEmailVerifyIndexRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authEmailResendIndexRoute: authEmailResendIndexRoute,
  authEmailVerifyIndexRoute: authEmailVerifyIndexRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface ProtectedRoutesDashboardRouteRouteChildren {
  ProtectedRoutesDashboardIndexRoute: typeof ProtectedRoutesDashboardIndexRoute
  ProtectedRoutesDashboardSessionsIndexRoute: typeof ProtectedRoutesDashboardSessionsIndexRoute
}

const ProtectedRoutesDashboardRouteRouteChildren: ProtectedRoutesDashboardRouteRouteChildren =
  {
    ProtectedRoutesDashboardIndexRoute: ProtectedRoutesDashboardIndexRoute,
    ProtectedRoutesDashboardSessionsIndexRoute:
      ProtectedRoutesDashboardSessionsIndexRoute,
  }

const ProtectedRoutesDashboardRouteRouteWithChildren =
  ProtectedRoutesDashboardRouteRoute._addFileChildren(
    ProtectedRoutesDashboardRouteRouteChildren,
  )

interface ProtectedRoutesRouteRouteChildren {
  ProtectedRoutesDashboardRouteRoute: typeof ProtectedRoutesDashboardRouteRouteWithChildren
}

const ProtectedRoutesRouteRouteChildren: ProtectedRoutesRouteRouteChildren = {
  ProtectedRoutesDashboardRouteRoute:
    ProtectedRoutesDashboardRouteRouteWithChildren,
}

const ProtectedRoutesRouteRouteWithChildren =
  ProtectedRoutesRouteRoute._addFileChildren(ProtectedRoutesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ProtectedRoutesRouteRoute: ProtectedRoutesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
